<a href="https://colab.research.google.com/github/dhruvsaxena11/Neural-Machine-Translation/blob/main/Language_Translation_Model_(Encoder_Decoder)_Dhruv_Saxena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("rd124/marian-finetuned-kde4-en-to-hi")
model = AutoModelForSeq2SeqLM.from_pretrained("rd124/marian-finetuned-kde4-en-to-hi")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/308 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/812k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/1.07M [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:197: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


config.json:   0%|          | 0.00/1.41k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/304M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/258 [00:00<?, ?B/s]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
from tensorflow import keras

In [ ]:
url = "https://raw.githubusercontent.com/suvaansh/Machine-Translation-English-to-Hindi-/master/hin.txt"
df = pd.read_table(url,header=None,names=["english","Hindi"])
df.head()

english    Hindi
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [ ]:
df.shape

(2869, 2)

In [ ]:
#english tokens
from keras.preprocessing.text import Tokenizer
eng_tk=Tokenizer()
eng_tk.fit_on_texts(df.english)
len(eng_tk.word_counts)


2402

In [ ]:
hin_tk=Tokenizer()
hin_tk.fit_on_texts(df.Hindi)
hin_tk.index_word[100]

'हो।'

In [ ]:
eng_x=eng_tk.texts_to_sequences(df.english)
eng_x

[[90],
 [556],
 [556],
 [556],
 [907],
 [907],
 [908],
 [908],
 [128, 11],
 [38, 909],
 [1285],
 [47, 9],
 [64, 60],
 [33, 152],
 [1286],
 [910],
 [910],
 [691],
 [691],
 [12, 284],
 [12, 284],
 [12, 284],
 [2, 351],
 [2, 351],
 [81, 468],
 [38, 911],
 [38, 1287],
 [182, 33],
 [167, 14],
 [404, 352],
 [405, 14],
 [1288],
 [2, 1289, 110],
 [2, 557],
 [38, 692],
 [38, 285],
 [38, 159],
 [52, 286],
 [91, 287],
 [91, 287],
 [91, 287],
 [91, 287],
 [693],
 [404, 558],
 [47, 26, 9],
 [1290],
 [28, 406],
 [353, 1291],
 [694, 27],
 [2, 58, 159],
 [2, 39, 354],
 [2, 39, 354],
 [2, 229, 4],
 [2, 229, 4],
 [2, 229, 4],
 [2, 229, 4],
 [2, 229, 4],
 [2, 23, 209],
 [38, 252],
 [38, 407],
 [38, 407],
 [142, 27, 9],
 [142, 27, 9],
 [142, 14, 60],
 [168, 129],
 [53, 310],
 [210, 160],
 [210, 160],
 [912, 20],
 [28, 695],
 [28, 695],
 [7, 559, 45],
 [230, 560],
 [36, 18, 4],
 [36, 18, 4],
 [36, 18, 4],
 [36, 18, 4],
 [36, 18, 4],
 [36, 18, 4],
 [36, 18, 4],
 [2, 58, 407],
 [2, 32, 194],
 [2, 32, 561],
 

In [ ]:
hin_y=hin_tk.texts_to_sequences(df.Hindi)
len(hin_y)

2869

In [ ]:
from keras.utils import pad_sequences
eng_x_new=pad_sequences(eng_x,padding="post")
hin_y_new=pad_sequences(hin_y,padding="post")
hin_y_new.shape

(2869, 25)

In [ ]:
my=hin_y_new.reshape(*hin_y_new.shape,1)
my[0]

array([[1466],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0]], dtype=int32)

In [ ]:
len(hin_y_new)

2869

In [ ]:
len(eng_x_new[5])

22

In [ ]:
len(hin_y_new[5])

25

In [ ]:
len(hin_y_new[:, :-1][0])

24

In [ ]:
len(hin_y_new[:, 1:][0])

24

In [ ]:
model=keras.Sequential([
    keras.layers.Embedding(input_dim=2403,output_dim=400,input_length=len(eng_x_new[0])),
    keras.layers.LSTM(1000,return_sequences=False),
    keras.layers.RepeatVector(25),
    keras.layers.LSTM(1000,return_sequences=True,dropout=0.1),
    keras.layers.TimeDistributed(keras.layers.Dense(3012,activation="softmax"))


])

model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

history=model.fit(eng_x_new,hin_y_new,epochs=50)

Epoch 1/50
90/90 [==============================] - 11s 73ms/step - loss: 2.2889 - accuracy: 0.7180
Epoch 2/50
90/90 [==============================] - 4s 48ms/step - loss: 1.9285 - accuracy: 0.7307
Epoch 3/50
90/90 [==============================] - 5s 58ms/step - loss: 1.9172 - accuracy: 0.7308
Epoch 4/50
90/90 [==============================] - 4s 42ms/step - loss: 1.8755 - accuracy: 0.7315
Epoch 5/50
90/90 [==============================] - 4s 42ms/step - loss: 1.8470 - accuracy: 0.7315
Epoch 6/50
90/90 [==============================] - 4s 42ms/step - loss: 1.8484 - accuracy: 0.7324
Epoch 7/50
90/90 [==============================] - 3s 37ms/step - loss: 1.8288 - accuracy: 0.7325
Epoch 8/50
90/90 [==============================] - 3s 39ms/step - loss: 1.8553 - accuracy: 0.7315
Epoch 9/50
90/90 [==============================] - 4s 41ms/step - loss: 1.8428 - accuracy: 0.7316
Epoch 10/50
90/90 [==============================] - 3s 37ms/step - loss: 1.8419 - accuracy: 0.7317
Epoch 11

In [ ]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 22)]                 0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 25)]                 0         []                            
                                                                                                  
 embedding (Embedding)       (None, 22, 400)              961200    ['input_1[0][0]']             
                                                                                                  
 embedding_1 (Embedding)     (None, 25, 400)              1204800   ['input_2[0][0]']             
                                                                                              

In [ ]:
eng_testing=eng_x_new.reshape(-1,22,1)
eng_testing[0]

array([[90],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0]], dtype=int32)

In [ ]:
model.predict(eng_testing[500])

1/1 [==============================] - 1s 656ms/step


array([[[2.00566574e-04, 1.00164623e-04, 3.28514772e-03, ...,
         6.74636567e-06, 6.90129446e-06, 7.51633024e-06],
        [2.93991208e-04, 4.84649936e-05, 4.72022146e-02, ...,
         5.66293863e-07, 2.95566053e-07, 4.08750225e-07],
        [2.65374954e-04, 8.49106000e-04, 7.66055733e-02, ...,
         1.62004781e-07, 1.40088247e-07, 1.78272586e-07],
        ...,
        [9.99996781e-01, 2.21154869e-06, 5.16539167e-09, ...,
         2.25445986e-12, 1.39649873e-18, 3.39272347e-18],
        [9.99996901e-01, 2.18468540e-06, 5.12133491e-09, ...,
         2.31691597e-12, 1.40590098e-18, 3.41155506e-18],
        [9.99996901e-01, 2.15999489e-06, 5.09263876e-09, ...,
         2.37430887e-12, 1.41771157e-18, 3.43084409e-18]],

       [[9.83150210e-03, 3.03690531e-03, 9.59100574e-03, ...,
         1.58808489e-05, 9.62483864e-06, 1.02612339e-05],
        [3.44412208e-01, 4.15139040e-03, 8.21996853e-03, ...,
         2.39982000e-06, 3.02130928e-07, 3.29484863e-07],
        [8.73656273e-01, 

In [ ]:
en=["name"]
en_new=eng_tk.texts_to_sequences(en)

en_x_new=pad_sequences(en_new,padding="post")
en_x_new

array([[291]], dtype=int32)

In [ ]:
# Assuming eng_testing[0] is a single English sequence
single_sequence = eng_testing[500]

# Reshape the sequence to have a batch size of 1
single_sequence = np.reshape(single_sequence, (1, len(single_sequence)))

# Get predictions
predictions = model.predict(np.array(single_sequence))


1/1 [==============================] - 1s 686ms/step


In [ ]:
predictions

array([[[4.6828309e-06, 3.1319561e-07, 2.4791376e-08, ...,
         4.5417206e-10, 3.1849545e-10, 6.1188082e-10],
        [1.3750045e-05, 8.2064986e-09, 7.7889712e-07, ...,
         1.3060440e-10, 1.1214181e-10, 1.6795737e-10],
        [8.4984604e-06, 3.4333052e-06, 8.6868175e-05, ...,
         1.2313636e-10, 1.5528473e-10, 2.0659885e-10],
        ...,
        [9.9999857e-01, 1.4021654e-06, 4.3511972e-09, ...,
         2.1467767e-16, 1.3701344e-16, 8.9874821e-17],
        [9.9999857e-01, 1.3796149e-06, 4.6615605e-09, ...,
         2.1041944e-16, 1.3450697e-16, 8.8017205e-17],
        [9.9999869e-01, 1.3667055e-06, 4.8626467e-09, ...,
         2.0741183e-16, 1.3282182e-16, 8.6745571e-17]]], dtype=float32)

In [ ]:
my=[]
for j in range(predictions.shape[1]):
    # Probabilities for the j-th token in the sequence
    probabilities_at_step = predictions[0, j, :]

    # Find the index of the token with the highest probability
    predicted_token_index = np.argmax(probabilities_at_step)

    # Print or use the predicted token index
    my.append(predicted_token_index)

In [ ]:
my

[43,
 816,
 1632,
 557,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [ ]:
df.english[500]

'We must pay the tax.'

In [ ]:
hin_tk.index_word[0]="<null>"
[hin_tk.index_word[x] for x in my]

['हम',
 'टैक्स',
 'भरना',
 'पड़ेगा।',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>',
 '<null>']

In [ ]:
hin_tk.index_word[0]

'<null>'